// Code generated by "stringer -type=CardSuit"; DO NOT EDIT.

package suits

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spade-1]
	_ = x[Diamond-2]
	_ = x[Heart-3]
	_ = x[Club-4]
	_ = x[Joker-5]
}

const _CardSuit_name = "SpadeDiamondHeartClubJoker"

var _CardSuit_index = [...]uint8{0, 5, 12, 17, 21, 26}

func (i CardSuit) String() string {
	i -= 1
	if i >= CardSuit(len(_CardSuit_index)-1) {
		return "CardSuit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CardSuit_name[_CardSuit_index[i]:_CardSuit_index[i+1]]
}
