// Code generated by "stringer -type=CardRank"; DO NOT EDIT.

package ranks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-1]
	_ = x[TWO-2]
	_ = x[THREE-3]
	_ = x[FOUR-4]
	_ = x[FIVE-5]
	_ = x[SIX-6]
	_ = x[SEVEN-7]
	_ = x[EIGHT-8]
	_ = x[NINE-9]
	_ = x[TEN-10]
	_ = x[Jack-11]
	_ = x[Queen-12]
	_ = x[King-13]
	_ = x[Joker-14]
}

const _CardRank_name = "AceTWOTHREEFOURFIVESIXSEVENEIGHTNINETENJackQueenKingJoker"

var _CardRank_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 43, 48, 52, 57}

func (i CardRank) String() string {
	i -= 1
	if i >= CardRank(len(_CardRank_index)-1) {
		return "CardRank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CardRank_name[_CardRank_index[i]:_CardRank_index[i+1]]
}
